//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreadedComments.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public Comment()
        {
            this.ParentComment = new HashSet<Comment>();
        }
    
        public int CommentId { get; set; }
        public int PostId { get; set; }
        public int BoardId { get; set; }
        public Nullable<int> ParentCommentId { get; set; }
        public string Body { get; set; }
        public string AuthorName { get; set; }
        public string AuthorEmail { get; set; }
        public System.DateTime CommentUtcDate { get; set; }
        public string SortOrder { get; set; }
        public int Indent { get; set; }
    
        public virtual Board Board { get; set; }
        public virtual ICollection<Comment> ParentComment { get; set; }
        public virtual Post Post { get; set; }
    }
}
