//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreadedComments.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public Post()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public int PostId { get; set; }
        public int BoardId { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public string AuthorName { get; set; }
        public string AuthorEmail { get; set; }
        public System.DateTime PostUtcDate { get; set; }
    
        public virtual Board Board { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
    }
}
